workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'
      when: always

stages:
  - verify

verify:
  stage: verify
  image: alpine:latest
  script:
    - echo "Repository with 3 files verified successfully"
